environment: prod

server:
  grpc_port: ":50051"
  http_port: ":8082"

db:
  host: localhost
  port: 5432
  ssl_mode: disable

redis:
  addr: localhost:6380
  db: 0
  ttl:
    user: 15m
    categories: 1h
    auth_block: 5m
    product: 5m
    admin: 15m
    claim: 20m
    code: 5m
    reset_password: 15m

kafka:
  topics:
    order_events: "order_events"
    transaction_events: "transaction_events"
    notifications: "notifications"
    notifications_dlq: "notification_dlq"
  brokers:
    - "kafka:9092"
  group_id: "servicehub-backend"

auth:
  access_token_ttl: 15m
  refresh_token_ttl: 168h

minio:
  endpoint: "localhost:9000"
  bucket: "servicehub-avatars"
  use_ssl: false

log:
  level: info

smtp:
  host: "smtp.yandex.ru"
  port: 465
