// Code generated by MockGen. DO NOT EDIT.
// Source: admin.go

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/nhassl3/servicehub-backend/internal/domain"
)

// MockAdminRepository is a mock of AdminRepository interface.
type MockAdminRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminRepositoryMockRecorder
}

// MockAdminRepositoryMockRecorder is the mock recorder for MockAdminRepository.
type MockAdminRepositoryMockRecorder struct {
	mock *MockAdminRepository
}

// NewMockAdminRepository creates a new mock instance.
func NewMockAdminRepository(ctrl *gomock.Controller) *MockAdminRepository {
	mock := &MockAdminRepository{ctrl: ctrl}
	mock.recorder = &MockAdminRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminRepository) EXPECT() *MockAdminRepositoryMockRecorder {
	return m.recorder
}

// CreateAdmin mocks base method.
func (m *MockAdminRepository) CreateAdmin(ctx context.Context, params domain.CreateAdminParams) (*domain.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdmin", ctx, params)
	ret0, _ := ret[0].(*domain.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdmin indicates an expected call of CreateAdmin.
func (mr *MockAdminRepositoryMockRecorder) CreateAdmin(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdmin", reflect.TypeOf((*MockAdminRepository)(nil).CreateAdmin), ctx, params)
}

// ExistsAdminByUsername mocks base method.
func (m *MockAdminRepository) ExistsAdminByUsername(ctx context.Context, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsAdminByUsername", ctx, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsAdminByUsername indicates an expected call of ExistsAdminByUsername.
func (mr *MockAdminRepositoryMockRecorder) ExistsAdminByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsAdminByUsername", reflect.TypeOf((*MockAdminRepository)(nil).ExistsAdminByUsername), ctx, username)
}

// GetAdmin mocks base method.
func (m *MockAdminRepository) GetAdmin(ctx context.Context, params domain.GetAdminProfileParams) (*domain.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdmin", ctx, params)
	ret0, _ := ret[0].(*domain.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdmin indicates an expected call of GetAdmin.
func (mr *MockAdminRepositoryMockRecorder) GetAdmin(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdmin", reflect.TypeOf((*MockAdminRepository)(nil).GetAdmin), ctx, params)
}

// IncreaseTotalModerates mocks base method.
func (m *MockAdminRepository) IncreaseTotalModerates(ctx context.Context, params domain.IncreaseTotalModeratesParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseTotalModerates", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseTotalModerates indicates an expected call of IncreaseTotalModerates.
func (mr *MockAdminRepositoryMockRecorder) IncreaseTotalModerates(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseTotalModerates", reflect.TypeOf((*MockAdminRepository)(nil).IncreaseTotalModerates), ctx, params)
}

// UpdateAdminProfile mocks base method.
func (m *MockAdminRepository) UpdateAdminProfile(ctx context.Context, params domain.UpdateAdminsProfileParams) (*domain.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdminProfile", ctx, params)
	ret0, _ := ret[0].(*domain.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAdminProfile indicates an expected call of UpdateAdminProfile.
func (mr *MockAdminRepositoryMockRecorder) UpdateAdminProfile(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdminProfile", reflect.TypeOf((*MockAdminRepository)(nil).UpdateAdminProfile), ctx, params)
}

// UploadCategoryAvatar mocks base method.
func (m *MockAdminRepository) UploadCategoryAvatar(ctx context.Context, params domain.UploadCategoryAvatar) (*domain.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadCategoryAvatar", ctx, params)
	ret0, _ := ret[0].(*domain.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadCategoryAvatar indicates an expected call of UploadCategoryAvatar.
func (mr *MockAdminRepositoryMockRecorder) UploadCategoryAvatar(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadCategoryAvatar", reflect.TypeOf((*MockAdminRepository)(nil).UploadCategoryAvatar), ctx, params)
}

// MockAdminRedis is a mock of AdminRedis interface.
type MockAdminRedis struct {
	ctrl     *gomock.Controller
	recorder *MockAdminRedisMockRecorder
}

// MockAdminRedisMockRecorder is the mock recorder for MockAdminRedis.
type MockAdminRedisMockRecorder struct {
	mock *MockAdminRedis
}

// NewMockAdminRedis creates a new mock instance.
func NewMockAdminRedis(ctrl *gomock.Controller) *MockAdminRedis {
	mock := &MockAdminRedis{ctrl: ctrl}
	mock.recorder = &MockAdminRedisMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminRedis) EXPECT() *MockAdminRedisMockRecorder {
	return m.recorder
}

// Profile mocks base method.
func (m *MockAdminRedis) Profile(ctx context.Context, username string) (*domain.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Profile", ctx, username)
	ret0, _ := ret[0].(*domain.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Profile indicates an expected call of Profile.
func (mr *MockAdminRedisMockRecorder) Profile(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Profile", reflect.TypeOf((*MockAdminRedis)(nil).Profile), ctx, username)
}

// SetProfile mocks base method.
func (m *MockAdminRedis) SetProfile(ctx context.Context, admin *domain.Admin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProfile", ctx, admin)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProfile indicates an expected call of SetProfile.
func (mr *MockAdminRedisMockRecorder) SetProfile(ctx, admin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProfile", reflect.TypeOf((*MockAdminRedis)(nil).SetProfile), ctx, admin)
}
