// Code generated by MockGen. DO NOT EDIT.
// Source: seller.go

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/nhassl3/servicehub/internal/domain"
)

// MockSellerRepository is a mock of SellerRepository interface.
type MockSellerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSellerRepositoryMockRecorder
}

// MockSellerRepositoryMockRecorder is the mock recorder for MockSellerRepository.
type MockSellerRepositoryMockRecorder struct {
	mock *MockSellerRepository
}

// NewMockSellerRepository creates a new mock instance.
func NewMockSellerRepository(ctrl *gomock.Controller) *MockSellerRepository {
	mock := &MockSellerRepository{ctrl: ctrl}
	mock.recorder = &MockSellerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSellerRepository) EXPECT() *MockSellerRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSellerRepository) Create(ctx context.Context, params domain.CreateSellerParams) (*domain.Seller, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*domain.Seller)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSellerRepositoryMockRecorder) Create(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSellerRepository)(nil).Create), ctx, params)
}

// ExistsByUsername mocks base method.
func (m *MockSellerRepository) ExistsByUsername(ctx context.Context, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByUsername", ctx, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByUsername indicates an expected call of ExistsByUsername.
func (mr *MockSellerRepositoryMockRecorder) ExistsByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByUsername", reflect.TypeOf((*MockSellerRepository)(nil).ExistsByUsername), ctx, username)
}

// GetSeller mocks base method.
func (m *MockSellerRepository) GetSeller(ctx context.Context, params domain.GetSellerProfileParams) (*domain.Seller, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeller", ctx, params)
	ret0, _ := ret[0].(*domain.Seller)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeller indicates an expected call of GetSeller.
func (mr *MockSellerRepositoryMockRecorder) GetSeller(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeller", reflect.TypeOf((*MockSellerRepository)(nil).GetSeller), ctx, params)
}

// Update mocks base method.
func (m *MockSellerRepository) Update(ctx context.Context, params domain.UpdateSellerParams) (*domain.Seller, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(*domain.Seller)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSellerRepositoryMockRecorder) Update(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSellerRepository)(nil).Update), ctx, params)
}
