// Code generated by MockGen. DO NOT EDIT.
// Source: analytics.go

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/nhassl3/servicehub-backend/internal/domain"
)

// MockAnalyticsRepository is a mock of AnalyticsRepository interface.
type MockAnalyticsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsRepositoryMockRecorder
}

// MockAnalyticsRepositoryMockRecorder is the mock recorder for MockAnalyticsRepository.
type MockAnalyticsRepositoryMockRecorder struct {
	mock *MockAnalyticsRepository
}

// NewMockAnalyticsRepository creates a new mock instance.
func NewMockAnalyticsRepository(ctrl *gomock.Controller) *MockAnalyticsRepository {
	mock := &MockAnalyticsRepository{ctrl: ctrl}
	mock.recorder = &MockAnalyticsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsRepository) EXPECT() *MockAnalyticsRepositoryMockRecorder {
	return m.recorder
}

// GetAdminStatistics mocks base method.
func (m *MockAnalyticsRepository) GetAdminStatistics(ctx context.Context, params domain.AdminStatisticsParams) (*domain.AdminStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminStatistics", ctx, params)
	ret0, _ := ret[0].(*domain.AdminStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminStatistics indicates an expected call of GetAdminStatistics.
func (mr *MockAnalyticsRepositoryMockRecorder) GetAdminStatistics(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminStatistics", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetAdminStatistics), ctx, params)
}

// InsertEvents mocks base method.
func (m *MockAnalyticsRepository) InsertEvents(ctx context.Context, events []domain.AnalyticsEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEvents", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEvents indicates an expected call of InsertEvents.
func (mr *MockAnalyticsRepositoryMockRecorder) InsertEvents(ctx, events interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEvents", reflect.TypeOf((*MockAnalyticsRepository)(nil).InsertEvents), ctx, events)
}
