// Code generated by MockGen. DO NOT EDIT.
// Source: cart.go

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/nhassl3/servicehub/internal/domain"
)

// MockCartRepository is a mock of CartRepository interface.
type MockCartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCartRepositoryMockRecorder
}

// MockCartRepositoryMockRecorder is the mock recorder for MockCartRepository.
type MockCartRepositoryMockRecorder struct {
	mock *MockCartRepository
}

// NewMockCartRepository creates a new mock instance.
func NewMockCartRepository(ctrl *gomock.Controller) *MockCartRepository {
	mock := &MockCartRepository{ctrl: ctrl}
	mock.recorder = &MockCartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartRepository) EXPECT() *MockCartRepositoryMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockCartRepository) AddItem(ctx context.Context, cartID int64, productID string, qty int) (*domain.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, cartID, productID, qty)
	ret0, _ := ret[0].(*domain.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddItem indicates an expected call of AddItem.
func (mr *MockCartRepositoryMockRecorder) AddItem(ctx, cartID, productID, qty interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockCartRepository)(nil).AddItem), ctx, cartID, productID, qty)
}

// Clear mocks base method.
func (m *MockCartRepository) Clear(ctx context.Context, cartID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx, cartID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockCartRepositoryMockRecorder) Clear(ctx, cartID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockCartRepository)(nil).Clear), ctx, cartID)
}

// GetItems mocks base method.
func (m *MockCartRepository) GetItems(ctx context.Context, cartID int64) ([]domain.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItems", ctx, cartID)
	ret0, _ := ret[0].([]domain.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItems indicates an expected call of GetItems.
func (mr *MockCartRepositoryMockRecorder) GetItems(ctx, cartID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItems", reflect.TypeOf((*MockCartRepository)(nil).GetItems), ctx, cartID)
}

// GetOrCreate mocks base method.
func (m *MockCartRepository) GetOrCreate(ctx context.Context, username string) (*domain.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreate", ctx, username)
	ret0, _ := ret[0].(*domain.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreate indicates an expected call of GetOrCreate.
func (mr *MockCartRepositoryMockRecorder) GetOrCreate(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreate", reflect.TypeOf((*MockCartRepository)(nil).GetOrCreate), ctx, username)
}

// RemoveItem mocks base method.
func (m *MockCartRepository) RemoveItem(ctx context.Context, cartID int64, productID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveItem", ctx, cartID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveItem indicates an expected call of RemoveItem.
func (mr *MockCartRepositoryMockRecorder) RemoveItem(ctx, cartID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItem", reflect.TypeOf((*MockCartRepository)(nil).RemoveItem), ctx, cartID, productID)
}

// UpdateItemQty mocks base method.
func (m *MockCartRepository) UpdateItemQty(ctx context.Context, cartID int64, productID string, qty int) (*domain.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItemQty", ctx, cartID, productID, qty)
	ret0, _ := ret[0].(*domain.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateItemQty indicates an expected call of UpdateItemQty.
func (mr *MockCartRepositoryMockRecorder) UpdateItemQty(ctx, cartID, productID, qty interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItemQty", reflect.TypeOf((*MockCartRepository)(nil).UpdateItemQty), ctx, cartID, productID, qty)
}
