// Code generated by MockGen. DO NOT EDIT.
// Source: event.go

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/nhassl3/servicehub-backend/internal/domain"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventPublisher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventPublisherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventPublisher)(nil).Close))
}

// PublishBalanceUpdated mocks base method.
func (m *MockEventPublisher) PublishBalanceUpdated(ctx context.Context, payload domain.BalanceUpdatedPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishBalanceUpdated", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishBalanceUpdated indicates an expected call of PublishBalanceUpdated.
func (mr *MockEventPublisherMockRecorder) PublishBalanceUpdated(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishBalanceUpdated", reflect.TypeOf((*MockEventPublisher)(nil).PublishBalanceUpdated), ctx, payload)
}

// PublishDeletedProduct mocks base method.
func (m *MockEventPublisher) PublishDeletedProduct(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDeletedProduct", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishDeletedProduct indicates an expected call of PublishDeletedProduct.
func (mr *MockEventPublisherMockRecorder) PublishDeletedProduct(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDeletedProduct", reflect.TypeOf((*MockEventPublisher)(nil).PublishDeletedProduct), ctx, id)
}

// PublishIndexedProduct mocks base method.
func (m *MockEventPublisher) PublishIndexedProduct(ctx context.Context, product *domain.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishIndexedProduct", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishIndexedProduct indicates an expected call of PublishIndexedProduct.
func (mr *MockEventPublisherMockRecorder) PublishIndexedProduct(ctx, product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishIndexedProduct", reflect.TypeOf((*MockEventPublisher)(nil).PublishIndexedProduct), ctx, product)
}

// PublishModerationApproved mocks base method.
func (m *MockEventPublisher) PublishModerationApproved(ctx context.Context, payload domain.ModerationApprovedPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishModerationApproved", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishModerationApproved indicates an expected call of PublishModerationApproved.
func (mr *MockEventPublisherMockRecorder) PublishModerationApproved(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishModerationApproved", reflect.TypeOf((*MockEventPublisher)(nil).PublishModerationApproved), ctx, payload)
}

// PublishModerationRejected mocks base method.
func (m *MockEventPublisher) PublishModerationRejected(ctx context.Context, payload domain.ModerationRejectedPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishModerationRejected", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishModerationRejected indicates an expected call of PublishModerationRejected.
func (mr *MockEventPublisherMockRecorder) PublishModerationRejected(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishModerationRejected", reflect.TypeOf((*MockEventPublisher)(nil).PublishModerationRejected), ctx, payload)
}

// PublishOrderCreated mocks base method.
func (m *MockEventPublisher) PublishOrderCreated(ctx context.Context, payload domain.OrderCreatedPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishOrderCreated", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishOrderCreated indicates an expected call of PublishOrderCreated.
func (mr *MockEventPublisherMockRecorder) PublishOrderCreated(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishOrderCreated", reflect.TypeOf((*MockEventPublisher)(nil).PublishOrderCreated), ctx, payload)
}

// PublishOrderItemCreated mocks base method.
func (m *MockEventPublisher) PublishOrderItemCreated(ctx context.Context, payload domain.OrderItemCreatedPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishOrderItemCreated", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishOrderItemCreated indicates an expected call of PublishOrderItemCreated.
func (mr *MockEventPublisherMockRecorder) PublishOrderItemCreated(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishOrderItemCreated", reflect.TypeOf((*MockEventPublisher)(nil).PublishOrderItemCreated), ctx, payload)
}

// PublishOrderStatusChanged mocks base method.
func (m *MockEventPublisher) PublishOrderStatusChanged(ctx context.Context, payload domain.OrderStatusChangedPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishOrderStatusChanged", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishOrderStatusChanged indicates an expected call of PublishOrderStatusChanged.
func (mr *MockEventPublisherMockRecorder) PublishOrderStatusChanged(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishOrderStatusChanged", reflect.TypeOf((*MockEventPublisher)(nil).PublishOrderStatusChanged), ctx, payload)
}

// PublishProductRatingChanged mocks base method.
func (m *MockEventPublisher) PublishProductRatingChanged(ctx context.Context, payload domain.ProductRatingChangedPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishProductRatingChanged", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishProductRatingChanged indicates an expected call of PublishProductRatingChanged.
func (mr *MockEventPublisherMockRecorder) PublishProductRatingChanged(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishProductRatingChanged", reflect.TypeOf((*MockEventPublisher)(nil).PublishProductRatingChanged), ctx, payload)
}

// PublishProductStatusChanged mocks base method.
func (m *MockEventPublisher) PublishProductStatusChanged(ctx context.Context, payload domain.ProductStatusChangedPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishProductStatusChanged", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishProductStatusChanged indicates an expected call of PublishProductStatusChanged.
func (mr *MockEventPublisherMockRecorder) PublishProductStatusChanged(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishProductStatusChanged", reflect.TypeOf((*MockEventPublisher)(nil).PublishProductStatusChanged), ctx, payload)
}

// PublishTransactionCreated mocks base method.
func (m *MockEventPublisher) PublishTransactionCreated(ctx context.Context, payload domain.TransactionCreatedPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishTransactionCreated", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishTransactionCreated indicates an expected call of PublishTransactionCreated.
func (mr *MockEventPublisherMockRecorder) PublishTransactionCreated(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishTransactionCreated", reflect.TypeOf((*MockEventPublisher)(nil).PublishTransactionCreated), ctx, payload)
}

// PublishUserRegistered mocks base method.
func (m *MockEventPublisher) PublishUserRegistered(ctx context.Context, payload domain.UserRegisteredPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishUserRegistered", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishUserRegistered indicates an expected call of PublishUserRegistered.
func (mr *MockEventPublisherMockRecorder) PublishUserRegistered(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUserRegistered", reflect.TypeOf((*MockEventPublisher)(nil).PublishUserRegistered), ctx, payload)
}
