// Code generated by MockGen. DO NOT EDIT.
// Source: moderation.go

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/nhassl3/servicehub/internal/domain"
)

// MockModerationRepository is a mock of ModerationRepository interface.
type MockModerationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockModerationRepositoryMockRecorder
}

// MockModerationRepositoryMockRecorder is the mock recorder for MockModerationRepository.
type MockModerationRepositoryMockRecorder struct {
	mock *MockModerationRepository
}

// NewMockModerationRepository creates a new mock instance.
func NewMockModerationRepository(ctrl *gomock.Controller) *MockModerationRepository {
	mock := &MockModerationRepository{ctrl: ctrl}
	mock.recorder = &MockModerationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModerationRepository) EXPECT() *MockModerationRepositoryMockRecorder {
	return m.recorder
}

// ClaimProduct mocks base method.
func (m *MockModerationRepository) ClaimProduct(ctx context.Context, params domain.ClaimProductParams) (*domain.Moderation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimProduct", ctx, params)
	ret0, _ := ret[0].(*domain.Moderation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimProduct indicates an expected call of ClaimProduct.
func (mr *MockModerationRepositoryMockRecorder) ClaimProduct(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimProduct", reflect.TypeOf((*MockModerationRepository)(nil).ClaimProduct), ctx, params)
}

// CreateModeration mocks base method.
func (m *MockModerationRepository) CreateModeration(ctx context.Context, params domain.CreateModerationParams) (*domain.Moderation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModeration", ctx, params)
	ret0, _ := ret[0].(*domain.Moderation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateModeration indicates an expected call of CreateModeration.
func (mr *MockModerationRepositoryMockRecorder) CreateModeration(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModeration", reflect.TypeOf((*MockModerationRepository)(nil).CreateModeration), ctx, params)
}

// GetModeration mocks base method.
func (m *MockModerationRepository) GetModeration(ctx context.Context, params domain.GetModerationParams) (*domain.Moderation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModeration", ctx, params)
	ret0, _ := ret[0].(*domain.Moderation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModeration indicates an expected call of GetModeration.
func (mr *MockModerationRepositoryMockRecorder) GetModeration(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModeration", reflect.TypeOf((*MockModerationRepository)(nil).GetModeration), ctx, params)
}

// MyReviews mocks base method.
func (m *MockModerationRepository) MyReviews(ctx context.Context, params domain.ListModerationParams) ([]*domain.QueueRow, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MyReviews", ctx, params)
	ret0, _ := ret[0].([]*domain.QueueRow)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// MyReviews indicates an expected call of MyReviews.
func (mr *MockModerationRepositoryMockRecorder) MyReviews(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MyReviews", reflect.TypeOf((*MockModerationRepository)(nil).MyReviews), ctx, params)
}

// Queue mocks base method.
func (m *MockModerationRepository) Queue(ctx context.Context, params domain.ListParams) ([]*domain.QueueRow, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Queue", ctx, params)
	ret0, _ := ret[0].([]*domain.QueueRow)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Queue indicates an expected call of Queue.
func (mr *MockModerationRepositoryMockRecorder) Queue(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Queue", reflect.TypeOf((*MockModerationRepository)(nil).Queue), ctx, params)
}

// ReleaseProduct mocks base method.
func (m *MockModerationRepository) ReleaseProduct(ctx context.Context, params domain.ReleaseProductParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseProduct", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseProduct indicates an expected call of ReleaseProduct.
func (mr *MockModerationRepositoryMockRecorder) ReleaseProduct(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseProduct", reflect.TypeOf((*MockModerationRepository)(nil).ReleaseProduct), ctx, params)
}

// Stats mocks base method.
func (m *MockModerationRepository) Stats(ctx context.Context, adminID string) (*domain.ModerationStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", ctx, adminID)
	ret0, _ := ret[0].(*domain.ModerationStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockModerationRepositoryMockRecorder) Stats(ctx, adminID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockModerationRepository)(nil).Stats), ctx, adminID)
}

// MockModerationLockRedis is a mock of ModerationLockRedis interface.
type MockModerationLockRedis struct {
	ctrl     *gomock.Controller
	recorder *MockModerationLockRedisMockRecorder
}

// MockModerationLockRedisMockRecorder is the mock recorder for MockModerationLockRedis.
type MockModerationLockRedisMockRecorder struct {
	mock *MockModerationLockRedis
}

// NewMockModerationLockRedis creates a new mock instance.
func NewMockModerationLockRedis(ctrl *gomock.Controller) *MockModerationLockRedis {
	mock := &MockModerationLockRedis{ctrl: ctrl}
	mock.recorder = &MockModerationLockRedisMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModerationLockRedis) EXPECT() *MockModerationLockRedisMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockModerationLockRedis) Acquire(ctx context.Context, productID, adminUsername string) (bool, *domain.ModerationLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx, productID, adminUsername)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*domain.ModerationLock)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Acquire indicates an expected call of Acquire.
func (mr *MockModerationLockRedisMockRecorder) Acquire(ctx, productID, adminUsername interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockModerationLockRedis)(nil).Acquire), ctx, productID, adminUsername)
}

// Get mocks base method.
func (m *MockModerationLockRedis) Get(ctx context.Context, productID string) (*domain.ModerationLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, productID)
	ret0, _ := ret[0].(*domain.ModerationLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockModerationLockRedisMockRecorder) Get(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockModerationLockRedis)(nil).Get), ctx, productID)
}

// Refresh mocks base method.
func (m *MockModerationLockRedis) Refresh(ctx context.Context, productID, adminUsername string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, productID, adminUsername)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refresh indicates an expected call of Refresh.
func (mr *MockModerationLockRedisMockRecorder) Refresh(ctx, productID, adminUsername interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockModerationLockRedis)(nil).Refresh), ctx, productID, adminUsername)
}

// Release mocks base method.
func (m *MockModerationLockRedis) Release(ctx context.Context, productID, adminUsername string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, productID, adminUsername)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockModerationLockRedisMockRecorder) Release(ctx, productID, adminUsername interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockModerationLockRedis)(nil).Release), ctx, productID, adminUsername)
}
