// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/nhassl3/servicehub-backend/internal/domain"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, params domain.CreateUserParams) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, params)
}

// CreateSession mocks base method.
func (m *MockUserRepository) CreateSession(ctx context.Context, params domain.CreateSessionParams) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, params)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockUserRepositoryMockRecorder) CreateSession(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockUserRepository)(nil).CreateSession), ctx, params)
}

// DeleteSession mocks base method.
func (m *MockUserRepository) DeleteSession(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockUserRepositoryMockRecorder) DeleteSession(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockUserRepository)(nil).DeleteSession), ctx, username)
}

// ExistsByEmail mocks base method.
func (m *MockUserRepository) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmail", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEmail indicates an expected call of ExistsByEmail.
func (mr *MockUserRepositoryMockRecorder) ExistsByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmail", reflect.TypeOf((*MockUserRepository)(nil).ExistsByEmail), ctx, email)
}

// ExistsByUsername mocks base method.
func (m *MockUserRepository) ExistsByUsername(ctx context.Context, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByUsername", ctx, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByUsername indicates an expected call of ExistsByUsername.
func (mr *MockUserRepositoryMockRecorder) ExistsByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByUsername", reflect.TypeOf((*MockUserRepository)(nil).ExistsByUsername), ctx, username)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
}

// GetByUID mocks base method.
func (m *MockUserRepository) GetByUID(ctx context.Context, uid string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUID", ctx, uid)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUID indicates an expected call of GetByUID.
func (mr *MockUserRepositoryMockRecorder) GetByUID(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUID", reflect.TypeOf((*MockUserRepository)(nil).GetByUID), ctx, uid)
}

// GetByUsername mocks base method.
func (m *MockUserRepository) GetByUsername(ctx context.Context, username string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockUserRepositoryMockRecorder) GetByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockUserRepository)(nil).GetByUsername), ctx, username)
}

// GetSession mocks base method.
func (m *MockUserRepository) GetSession(ctx context.Context, refreshToken string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, refreshToken)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockUserRepositoryMockRecorder) GetSession(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockUserRepository)(nil).GetSession), ctx, refreshToken)
}

// GetSessionByUsername mocks base method.
func (m *MockUserRepository) GetSessionByUsername(ctx context.Context, username string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByUsername", ctx, username)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByUsername indicates an expected call of GetSessionByUsername.
func (mr *MockUserRepositoryMockRecorder) GetSessionByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByUsername", reflect.TypeOf((*MockUserRepository)(nil).GetSessionByUsername), ctx, username)
}

// Update mocks base method.
func (m *MockUserRepository) Update(ctx context.Context, params domain.UpdateUserParams) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), ctx, params)
}

// UpdatePassword mocks base method.
func (m *MockUserRepository) UpdatePassword(ctx context.Context, params domain.UpdateUserPasswordParams) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, params)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserRepositoryMockRecorder) UpdatePassword(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserRepository)(nil).UpdatePassword), ctx, params)
}

// VerifyEmail mocks base method.
func (m *MockUserRepository) VerifyEmail(ctx context.Context, params domain.VerifyEmailAccount) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmail", ctx, params)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyEmail indicates an expected call of VerifyEmail.
func (mr *MockUserRepositoryMockRecorder) VerifyEmail(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmail", reflect.TypeOf((*MockUserRepository)(nil).VerifyEmail), ctx, params)
}

// MockUserRedis is a mock of UserRedis interface.
type MockUserRedis struct {
	ctrl     *gomock.Controller
	recorder *MockUserRedisMockRecorder
}

// MockUserRedisMockRecorder is the mock recorder for MockUserRedis.
type MockUserRedisMockRecorder struct {
	mock *MockUserRedis
}

// NewMockUserRedis creates a new mock instance.
func NewMockUserRedis(ctrl *gomock.Controller) *MockUserRedis {
	mock := &MockUserRedis{ctrl: ctrl}
	mock.recorder = &MockUserRedisMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRedis) EXPECT() *MockUserRedisMockRecorder {
	return m.recorder
}

// AuthBlock mocks base method.
func (m *MockUserRedis) AuthBlock(ctx context.Context, clientIP string) (bool, float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthBlock", ctx, clientIP)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AuthBlock indicates an expected call of AuthBlock.
func (mr *MockUserRedisMockRecorder) AuthBlock(ctx, clientIP interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthBlock", reflect.TypeOf((*MockUserRedis)(nil).AuthBlock), ctx, clientIP)
}

// Code mocks base method.
func (m *MockUserRedis) Code(ctx context.Context, enterKeyCode, operationId string) (*domain.ResetPasswordState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Code", ctx, enterKeyCode, operationId)
	ret0, _ := ret[0].(*domain.ResetPasswordState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Code indicates an expected call of Code.
func (mr *MockUserRedisMockRecorder) Code(ctx, enterKeyCode, operationId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Code", reflect.TypeOf((*MockUserRedis)(nil).Code), ctx, enterKeyCode, operationId)
}

// CodeExists mocks base method.
func (m *MockUserRedis) CodeExists(ctx context.Context, entryKeyCode, email string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CodeExists", ctx, entryKeyCode, email)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CodeExists indicates an expected call of CodeExists.
func (mr *MockUserRedisMockRecorder) CodeExists(ctx, entryKeyCode, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CodeExists", reflect.TypeOf((*MockUserRedis)(nil).CodeExists), ctx, entryKeyCode, email)
}

// DelCode mocks base method.
func (m *MockUserRedis) DelCode(ctx context.Context, enterKeyCode, operationId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelCode", ctx, enterKeyCode, operationId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelCode indicates an expected call of DelCode.
func (mr *MockUserRedisMockRecorder) DelCode(ctx, enterKeyCode, operationId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelCode", reflect.TypeOf((*MockUserRedis)(nil).DelCode), ctx, enterKeyCode, operationId)
}

// DelProfile mocks base method.
func (m *MockUserRedis) DelProfile(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelProfile", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelProfile indicates an expected call of DelProfile.
func (mr *MockUserRedisMockRecorder) DelProfile(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelProfile", reflect.TypeOf((*MockUserRedis)(nil).DelProfile), ctx, username)
}

// DelSession mocks base method.
func (m *MockUserRedis) DelSession(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelSession", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelSession indicates an expected call of DelSession.
func (mr *MockUserRedisMockRecorder) DelSession(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelSession", reflect.TypeOf((*MockUserRedis)(nil).DelSession), ctx, username)
}

// DelVerified mocks base method.
func (m *MockUserRedis) DelVerified(ctx context.Context, entryCode, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelVerified", ctx, entryCode, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelVerified indicates an expected call of DelVerified.
func (mr *MockUserRedisMockRecorder) DelVerified(ctx, entryCode, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelVerified", reflect.TypeOf((*MockUserRedis)(nil).DelVerified), ctx, entryCode, token)
}

// Profile mocks base method.
func (m *MockUserRedis) Profile(ctx context.Context, username string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Profile", ctx, username)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Profile indicates an expected call of Profile.
func (mr *MockUserRedisMockRecorder) Profile(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Profile", reflect.TypeOf((*MockUserRedis)(nil).Profile), ctx, username)
}

// Session mocks base method.
func (m *MockUserRedis) Session(ctx context.Context, username string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session", ctx, username)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Session indicates an expected call of Session.
func (mr *MockUserRedisMockRecorder) Session(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*MockUserRedis)(nil).Session), ctx, username)
}

// SetAuthBlock mocks base method.
func (m *MockUserRedis) SetAuthBlock(ctx context.Context, clientIP string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAuthBlock", ctx, clientIP)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAuthBlock indicates an expected call of SetAuthBlock.
func (mr *MockUserRedisMockRecorder) SetAuthBlock(ctx, clientIP interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAuthBlock", reflect.TypeOf((*MockUserRedis)(nil).SetAuthBlock), ctx, clientIP)
}

// SetCode mocks base method.
func (m *MockUserRedis) SetCode(ctx context.Context, enterKeyCode, operationId string, code *domain.ResetPasswordState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCode", ctx, enterKeyCode, operationId, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCode indicates an expected call of SetCode.
func (mr *MockUserRedisMockRecorder) SetCode(ctx, enterKeyCode, operationId, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCode", reflect.TypeOf((*MockUserRedis)(nil).SetCode), ctx, enterKeyCode, operationId, code)
}

// SetProfile mocks base method.
func (m *MockUserRedis) SetProfile(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProfile", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProfile indicates an expected call of SetProfile.
func (mr *MockUserRedisMockRecorder) SetProfile(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProfile", reflect.TypeOf((*MockUserRedis)(nil).SetProfile), ctx, user)
}

// SetSession mocks base method.
func (m *MockUserRedis) SetSession(ctx context.Context, session *domain.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSession indicates an expected call of SetSession.
func (mr *MockUserRedisMockRecorder) SetSession(ctx, session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSession", reflect.TypeOf((*MockUserRedis)(nil).SetSession), ctx, session)
}

// SetVerified mocks base method.
func (m *MockUserRedis) SetVerified(ctx context.Context, entryCode, token, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVerified", ctx, entryCode, token, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetVerified indicates an expected call of SetVerified.
func (mr *MockUserRedisMockRecorder) SetVerified(ctx, entryCode, token, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVerified", reflect.TypeOf((*MockUserRedis)(nil).SetVerified), ctx, entryCode, token, email)
}

// Verified mocks base method.
func (m *MockUserRedis) Verified(ctx context.Context, entryCode, token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verified", ctx, entryCode, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verified indicates an expected call of Verified.
func (mr *MockUserRedisMockRecorder) Verified(ctx, entryCode, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verified", reflect.TypeOf((*MockUserRedis)(nil).Verified), ctx, entryCode, token)
}
