// Code generated by MockGen. DO NOT EDIT.
// Source: wishlist.go

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/nhassl3/servicehub-backend/internal/domain"
)

// MockWishlistRepository is a mock of WishlistRepository interface.
type MockWishlistRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWishlistRepositoryMockRecorder
}

// MockWishlistRepositoryMockRecorder is the mock recorder for MockWishlistRepository.
type MockWishlistRepositoryMockRecorder struct {
	mock *MockWishlistRepository
}

// NewMockWishlistRepository creates a new mock instance.
func NewMockWishlistRepository(ctrl *gomock.Controller) *MockWishlistRepository {
	mock := &MockWishlistRepository{ctrl: ctrl}
	mock.recorder = &MockWishlistRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWishlistRepository) EXPECT() *MockWishlistRepositoryMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockWishlistRepository) Exists(ctx context.Context, username, productID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, username, productID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockWishlistRepositoryMockRecorder) Exists(ctx, username, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockWishlistRepository)(nil).Exists), ctx, username, productID)
}

// GetItems mocks base method.
func (m *MockWishlistRepository) GetItems(ctx context.Context, username string) ([]domain.WishlistItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItems", ctx, username)
	ret0, _ := ret[0].([]domain.WishlistItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItems indicates an expected call of GetItems.
func (mr *MockWishlistRepositoryMockRecorder) GetItems(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItems", reflect.TypeOf((*MockWishlistRepository)(nil).GetItems), ctx, username)
}

// RemoveItem mocks base method.
func (m *MockWishlistRepository) RemoveItem(ctx context.Context, username, productID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveItem", ctx, username, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveItem indicates an expected call of RemoveItem.
func (mr *MockWishlistRepositoryMockRecorder) RemoveItem(ctx, username, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItem", reflect.TypeOf((*MockWishlistRepository)(nil).RemoveItem), ctx, username, productID)
}

// ToggleWishlistItem mocks base method.
func (m *MockWishlistRepository) ToggleWishlistItem(ctx context.Context, username, productID string) (*domain.WishlistItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleWishlistItem", ctx, username, productID)
	ret0, _ := ret[0].(*domain.WishlistItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleWishlistItem indicates an expected call of ToggleWishlistItem.
func (mr *MockWishlistRepositoryMockRecorder) ToggleWishlistItem(ctx, username, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleWishlistItem", reflect.TypeOf((*MockWishlistRepository)(nil).ToggleWishlistItem), ctx, username, productID)
}
