// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admins.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getAdminById = `-- name: GetAdminById :one
SELECT id, username, display_name, level_rights, total_moderation, created_at, updated_at FROM admins WHERE id=$1
`

func (q *Queries) GetAdminById(ctx context.Context, id uuid.UUID) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminById, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.LevelRights,
		&i.TotalModeration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, display_name, level_rights, total_moderation, created_at, updated_at FROM admins WHERE username=$1
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.LevelRights,
		&i.TotalModeration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminUsernameByProductId = `-- name: GetAdminUsernameByProductId :one
SELECT username FROM admins
                WHERE id=(SELECT admin_id FROM moderation WHERE product_id=$1)
`

func (q *Queries) GetAdminUsernameByProductId(ctx context.Context, productID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getAdminUsernameByProductId, productID)
	var username string
	err := row.Scan(&username)
	return username, err
}
