// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balances.sql

package db

import (
	"context"
)

const addToBalance = `-- name: AddToBalance :one
INSERT INTO balances (username, amount)
VALUES ($1, $2)
ON CONFLICT (username)
DO UPDATE SET amount     = balances.amount + EXCLUDED.amount,
              updated_at = NOW()
RETURNING username, amount, updated_at
`

type AddToBalanceParams struct {
	Username string  `json:"username"`
	Amount   float64 `json:"amount"`
}

func (q *Queries) AddToBalance(ctx context.Context, arg AddToBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, addToBalance, arg.Username, arg.Amount)
	var i Balance
	err := row.Scan(&i.Username, &i.Amount, &i.UpdatedAt)
	return i, err
}

const deductFromBalance = `-- name: DeductFromBalance :one
UPDATE balances
SET amount     = amount - $2,
    updated_at = NOW()
WHERE username = $1
RETURNING username, amount, updated_at
`

type DeductFromBalanceParams struct {
	Username string  `json:"username"`
	Amount   float64 `json:"amount"`
}

func (q *Queries) DeductFromBalance(ctx context.Context, arg DeductFromBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, deductFromBalance, arg.Username, arg.Amount)
	var i Balance
	err := row.Scan(&i.Username, &i.Amount, &i.UpdatedAt)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT username, amount, updated_at
FROM balances
WHERE username = $1
`

func (q *Queries) GetBalance(ctx context.Context, username string) (Balance, error) {
	row := q.db.QueryRow(ctx, getBalance, username)
	var i Balance
	err := row.Scan(&i.Username, &i.Amount, &i.UpdatedAt)
	return i, err
}

const getBalanceForUpdate = `-- name: GetBalanceForUpdate :one
SELECT username, amount
FROM balances
WHERE username = $1
FOR UPDATE
`

type GetBalanceForUpdateRow struct {
	Username string  `json:"username"`
	Amount   float64 `json:"amount"`
}

func (q *Queries) GetBalanceForUpdate(ctx context.Context, username string) (GetBalanceForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getBalanceForUpdate, username)
	var i GetBalanceForUpdateRow
	err := row.Scan(&i.Username, &i.Amount)
	return i, err
}

const upsertBalance = `-- name: UpsertBalance :one
INSERT INTO balances (username)
VALUES ($1)
ON CONFLICT (username) DO UPDATE SET username = EXCLUDED.username
RETURNING username, amount, updated_at
`

func (q *Queries) UpsertBalance(ctx context.Context, username string) (Balance, error) {
	row := q.db.QueryRow(ctx, upsertBalance, username)
	var i Balance
	err := row.Scan(&i.Username, &i.Amount, &i.UpdatedAt)
	return i, err
}
