// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balance_transactions.sql

package db

import (
	"context"
)

const countBalanceTxByUsername = `-- name: CountBalanceTxByUsername :one
SELECT COUNT(*) FROM balance_transactions WHERE username = $1
`

func (q *Queries) CountBalanceTxByUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRow(ctx, countBalanceTxByUsername, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBalanceTx = `-- name: CreateBalanceTx :one
INSERT INTO balance_transactions (username, type, amount, comment)
VALUES ($1, $2, $3, $4)
RETURNING id, username, type, amount, comment, created_at
`

type CreateBalanceTxParams struct {
	Username string  `json:"username"`
	Type     string  `json:"type"`
	Amount   float64 `json:"amount"`
	Comment  string  `json:"comment"`
}

func (q *Queries) CreateBalanceTx(ctx context.Context, arg CreateBalanceTxParams) (BalanceTransaction, error) {
	row := q.db.QueryRow(ctx, createBalanceTx,
		arg.Username,
		arg.Type,
		arg.Amount,
		arg.Comment,
	)
	var i BalanceTransaction
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Type,
		&i.Amount,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const listBalanceTxByUsername = `-- name: ListBalanceTxByUsername :many
SELECT id, username, type, amount, comment, created_at
FROM balance_transactions
WHERE username = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBalanceTxByUsernameParams struct {
	Username string `json:"username"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListBalanceTxByUsername(ctx context.Context, arg ListBalanceTxByUsernameParams) ([]BalanceTransaction, error) {
	rows, err := q.db.Query(ctx, listBalanceTxByUsername, arg.Username, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceTransaction{}
	for rows.Next() {
		var i BalanceTransaction
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Type,
			&i.Amount,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
