// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart_items.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items WHERE cart_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, cartID int64) error {
	_, err := q.db.Exec(ctx, clearCart, cartID)
	return err
}

const deleteCartItem = `-- name: DeleteCartItem :execrows
DELETE FROM cart_items
WHERE cart_id = $1 AND product_id = $2
`

type DeleteCartItemParams struct {
	CartID    int64     `json:"cart_id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCartItem, arg.CartID, arg.ProductID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCartItems = `-- name: GetCartItems :many
SELECT id, cart_id, product_id, quantity, unit_price
FROM cart_items
WHERE cart_id = $1
`

func (q *Queries) GetCartItems(ctx context.Context, cartID int64) ([]CartItem, error) {
	rows, err := q.db.Query(ctx, getCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartItem{}
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductPrice = `-- name: GetProductPrice :one
SELECT price FROM products WHERE id = $1
`

func (q *Queries) GetProductPrice(ctx context.Context, id uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getProductPrice, id)
	var price float64
	err := row.Scan(&price)
	return price, err
}

const updateCartItemQty = `-- name: UpdateCartItemQty :one
UPDATE cart_items
SET quantity = $3
WHERE cart_id = $1 AND product_id = $2
RETURNING id, cart_id, product_id, quantity, unit_price
`

type UpdateCartItemQtyParams struct {
	CartID    int64     `json:"cart_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
}

func (q *Queries) UpdateCartItemQty(ctx context.Context, arg UpdateCartItemQtyParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQty, arg.CartID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
	)
	return i, err
}

const upsertCartItem = `-- name: UpsertCartItem :one
INSERT INTO cart_items (cart_id, product_id, quantity, unit_price)
VALUES ($1, $2, $3, $4)
ON CONFLICT (cart_id, product_id)
DO UPDATE SET quantity = cart_items.quantity + EXCLUDED.quantity
RETURNING id, cart_id, product_id, quantity, unit_price
`

type UpsertCartItemParams struct {
	CartID    int64     `json:"cart_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
	UnitPrice float64   `json:"unit_price"`
}

func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, upsertCartItem,
		arg.CartID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
	)
	return i, err
}
