// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: carts.sql

package db

import (
	"context"
)

const upsertCart = `-- name: UpsertCart :one
INSERT INTO carts (username)
VALUES ($1)
ON CONFLICT (username) DO UPDATE SET username = EXCLUDED.username
RETURNING id, username
`

type UpsertCartRow struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) UpsertCart(ctx context.Context, username string) (UpsertCartRow, error) {
	row := q.db.QueryRow(ctx, upsertCart, username)
	var i UpsertCartRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}
