// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approve = `-- name: Approve :exec

UPDATE products SET status='active' WHERE id=$1
`

// clean up redis lock storage for next methods (Approve, Reject)
func (q *Queries) Approve(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, approve, id)
	return err
}

const createModeration = `-- name: CreateModeration :one
INSERT INTO moderation (product_id, admin_id, active)
VALUES ($1, $2, true)
ON CONFLICT (product_id)
DO UPDATE SET active = true, admin_id = excluded.admin_id, updated_at = NOW()
RETURNING id, admin_id, product_id, active, created_at, updated_at, reason, status
`

type CreateModerationParams struct {
	ProductID uuid.UUID `json:"product_id"`
	AdminID   uuid.UUID `json:"admin_id"`
}

func (q *Queries) CreateModeration(ctx context.Context, arg CreateModerationParams) (Moderation, error) {
	row := q.db.QueryRow(ctx, createModeration, arg.ProductID, arg.AdminID)
	var i Moderation
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.ProductID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Reason,
		&i.Status,
	)
	return i, err
}

const getModeration = `-- name: GetModeration :one
SELECT id, admin_id, product_id, active, created_at, updated_at, reason, status FROM moderation WHERE id=$1 LIMIT 1
`

func (q *Queries) GetModeration(ctx context.Context, id uuid.UUID) (Moderation, error) {
	row := q.db.QueryRow(ctx, getModeration, id)
	var i Moderation
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.ProductID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Reason,
		&i.Status,
	)
	return i, err
}

const listModerationItems = `-- name: ListModerationItems :many
SELECT
    p.id, p.seller_id, p.category_id, p.title, p.description, p.price, p.tags, p.status, p.sales_count, p.rating, p.reviews_count, p.fts, p.created_at, p.updated_at,
    a.username AS admin_username,
    m.id, m.admin_id, m.product_id, m.active, m.created_at, m.updated_at, m.reason, m.status
FROM products p
         LEFT JOIN moderation m ON p.id = m.product_id
         LEFT JOIN admins a ON a.id = m.admin_id
WHERE
    ($1::uuid IS NULL AND p.status = 'draft')
   OR
    (m.admin_id = $1::uuid AND m.active = true)
ORDER BY m.created_at DESC
LIMIT $3 OFFSET $2
`

type ListModerationItemsParams struct {
	AdminID pgtype.UUID `json:"admin_id"`
	Offset  int32       `json:"offset"`
	Limit   int32       `json:"limit"`
}

type ListModerationItemsRow struct {
	Product       Product     `json:"product"`
	AdminUsername pgtype.Text `json:"admin_username"`
	Moderation    Moderation  `json:"moderation"`
}

func (q *Queries) ListModerationItems(ctx context.Context, arg ListModerationItemsParams) ([]ListModerationItemsRow, error) {
	rows, err := q.db.Query(ctx, listModerationItems, arg.AdminID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModerationItemsRow{}
	for rows.Next() {
		var i ListModerationItemsRow
		if err := rows.Scan(
			&i.Product.ID,
			&i.Product.SellerID,
			&i.Product.CategoryID,
			&i.Product.Title,
			&i.Product.Description,
			&i.Product.Price,
			&i.Product.Tags,
			&i.Product.Status,
			&i.Product.SalesCount,
			&i.Product.Rating,
			&i.Product.ReviewsCount,
			&i.Product.Fts,
			&i.Product.CreatedAt,
			&i.Product.UpdatedAt,
			&i.AdminUsername,
			&i.Moderation.ID,
			&i.Moderation.AdminID,
			&i.Moderation.ProductID,
			&i.Moderation.Active,
			&i.Moderation.CreatedAt,
			&i.Moderation.UpdatedAt,
			&i.Moderation.Reason,
			&i.Moderation.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reject = `-- name: Reject :exec
UPDATE products SET status='inactive' WHERE id=$1
`

func (q *Queries) Reject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, reject, id)
	return err
}

const release = `-- name: Release :exec
WITH updated AS (
    UPDATE moderation m SET active = false, status = $1, updated_at = NOW()
    WHERE m.product_id = $2
    RETURNING m.product_id, m.status
)
DELETE FROM moderation a
WHERE a.product_id = (SELECT u.product_id FROM updated u WHERE u.status = 'draft')
`

type ReleaseParams struct {
	Status    string    `json:"status"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) Release(ctx context.Context, arg ReleaseParams) error {
	_, err := q.db.Exec(ctx, release, arg.Status, arg.ProductID)
	return err
}

const total = `-- name: Total :one
SELECT COUNT(*)
FROM moderation
WHERE ($2::uuid IS NULL OR admin_id = $2::uuid)
    AND ($3::text IS NULL OR status = $3::text)
    AND active = $1
`

type TotalParams struct {
	Active  bool        `json:"active"`
	AdminID pgtype.UUID `json:"admin_id"`
	Status  pgtype.Text `json:"status"`
}

func (q *Queries) Total(ctx context.Context, arg TotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, total, arg.Active, arg.AdminID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}
