// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Balance struct {
	Username  string             `json:"username"`
	Amount    float64            `json:"amount"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type BalanceTransaction struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	Type      string             `json:"type"`
	Amount    float64            `json:"amount"`
	Comment   string             `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Cart struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CartItem struct {
	ID        int64     `json:"id"`
	CartID    int64     `json:"cart_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
	UnitPrice float64   `json:"unit_price"`
}

type Category struct {
	ID          int32              `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	IconUrl     string             `json:"icon_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Order struct {
	ID          uuid.UUID          `json:"id"`
	Uid         uuid.UUID          `json:"uid"`
	Username    string             `json:"username"`
	Status      string             `json:"status"`
	TotalAmount float64            `json:"total_amount"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID         int64          `json:"id"`
	OrderID    uuid.UUID      `json:"order_id"`
	ProductID  uuid.UUID      `json:"product_id"`
	Quantity   int32          `json:"quantity"`
	UnitPrice  float64        `json:"unit_price"`
	TotalPrice pgtype.Numeric `json:"total_price"`
}

type Product struct {
	ID           uuid.UUID          `json:"id"`
	SellerID     uuid.UUID          `json:"seller_id"`
	CategoryID   int32              `json:"category_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Price        float64            `json:"price"`
	Tags         []string           `json:"tags"`
	Status       string             `json:"status"`
	SalesCount   int32              `json:"sales_count"`
	Rating       float64            `json:"rating"`
	ReviewsCount int32              `json:"reviews_count"`
	Fts          interface{}        `json:"fts"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Review struct {
	ID        int64              `json:"id"`
	ProductID uuid.UUID          `json:"product_id"`
	Username  string             `json:"username"`
	Rating    int16              `json:"rating"`
	Comment   string             `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Seller struct {
	ID          uuid.UUID          `json:"id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	Description string             `json:"description"`
	AvatarUrl   string             `json:"avatar_url"`
	Rating      float64            `json:"rating"`
	TotalSales  int32              `json:"total_sales"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	Username     string             `json:"username"`
	Uid          uuid.UUID          `json:"uid"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	AvatarUrl    string             `json:"avatar_url"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Wishlist struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	ProductID uuid.UUID          `json:"product_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
