// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moderation.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getModerationByAdminId = `-- name: GetModerationByAdminId :one
SELECT id, admin_id, product_id, active, created_at, updated_at FROM moderation WHERE admin_id=$1
`

func (q *Queries) GetModerationByAdminId(ctx context.Context, adminID uuid.UUID) (Moderation, error) {
	row := q.db.QueryRow(ctx, getModerationByAdminId, adminID)
	var i Moderation
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.ProductID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModerationByProductId = `-- name: GetModerationByProductId :one
SELECT id, admin_id, product_id, active, created_at, updated_at FROM moderation WHERE product_id=$1
`

func (q *Queries) GetModerationByProductId(ctx context.Context, productID uuid.UUID) (Moderation, error) {
	row := q.db.QueryRow(ctx, getModerationByProductId, productID)
	var i Moderation
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.ProductID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, admin_id, product_id, active, created_at, updated_at FROM moderation
WHERE active=true
ORDER BY product_id
LIMIT $1 OFFSET $2
`

type ListActiveProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActiveProducts(ctx context.Context, arg ListActiveProductsParams) ([]Moderation, error) {
	rows, err := q.db.Query(ctx, listActiveProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Moderation{}
	for rows.Next() {
		var i Moderation
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.ProductID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
