// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
insert into notifications (username, message, group_of_message) VALUES ($1, $2, (select id from notification_group where slug=$3)) returning id
`

type CreateNotificationParams struct {
	Username string `json:"username"`
	Message  string `json:"message"`
	Slug     string `json:"slug"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createNotification, arg.Username, arg.Message, arg.Slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getNotification = `-- name: GetNotification :one
select id, username, message, group_of_message, created_at from notifications where id=$1
`

func (q *Queries) GetNotification(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Message,
		&i.GroupOfMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listNotification = `-- name: ListNotification :many
select id, username, message, group_of_message, created_at from notifications n
    where
        ($1::uuid is null or n.username=(select username from users u where u.id=$1))
        AND ($2::varchar is null or n.username=$2)
ORDER BY n.created_at DESC
LIMIT 10 OFFSET $3
`

type ListNotificationParams struct {
	ToUserID       pgtype.UUID `json:"to_user_id"`
	ToUserUsername pgtype.Text `json:"to_user_username"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListNotification(ctx context.Context, arg ListNotificationParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotification, arg.ToUserID, arg.ToUserUsername, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Message,
			&i.GroupOfMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
