// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countOrdersByUsername = `-- name: CountOrdersByUsername :one
SELECT COUNT(*)
FROM orders
WHERE username = $1
  AND ($2::text = '' OR status = $2)
`

type CountOrdersByUsernameParams struct {
	Username     string `json:"username"`
	FilterStatus string `json:"filter_status"`
}

func (q *Queries) CountOrdersByUsername(ctx context.Context, arg CountOrdersByUsernameParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByUsername, arg.Username, arg.FilterStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (username)
VALUES ($1)
RETURNING id, uid, username, status, total_amount, created_at, updated_at
`

func (q *Queries) CreateOrder(ctx context.Context, username string) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, username)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Username,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, uid, username, status, total_amount, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Username,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByUID = `-- name: GetOrderByUID :one
SELECT id, uid, username, status, total_amount, created_at, updated_at
FROM orders
WHERE uid = $1
`

func (q *Queries) GetOrderByUID(ctx context.Context, uid uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByUID, uid)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Username,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrdersByUsername = `-- name: ListOrdersByUsername :many
SELECT id, uid, username, status, total_amount, created_at, updated_at
FROM orders
WHERE username = $1
  AND ($2::text = '' OR status = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListOrdersByUsernameParams struct {
	Username     string `json:"username"`
	FilterStatus string `json:"filter_status"`
	Offset       int32  `json:"offset_"`
	Limit        int32  `json:"limit_"`
}

func (q *Queries) ListOrdersByUsername(ctx context.Context, arg ListOrdersByUsernameParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUsername,
		arg.Username,
		arg.FilterStatus,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.Username,
			&i.Status,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status     = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, uid, username, status, total_amount, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Username,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderTotal = `-- name: UpdateOrderTotal :one
UPDATE orders
SET total_amount = $2,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, uid, username, status, total_amount, created_at, updated_at
`

type UpdateOrderTotalParams struct {
	ID          uuid.UUID `json:"id"`
	TotalAmount float64   `json:"total_amount"`
}

func (q *Queries) UpdateOrderTotal(ctx context.Context, arg UpdateOrderTotalParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderTotal, arg.ID, arg.TotalAmount)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Username,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
