// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countListProducts = `-- name: CountListProducts :one
SELECT COUNT(*)
FROM products
WHERE ($1::uuid IS NULL OR seller_id = $1::uuid)
  AND ($2::int IS NULL OR category_id = $2::int)
  AND ($3::numeric IS NULL OR price >= $3::numeric)
  AND ($4::numeric IS NULL OR price <= $4::numeric)
  AND status = $5
`

type CountListProductsParams struct {
	SellerID   pgtype.UUID    `json:"seller_id"`
	CategoryID pgtype.Int4    `json:"category_id"`
	MinPrice   pgtype.Numeric `json:"min_price"`
	MaxPrice   pgtype.Numeric `json:"max_price"`
	Status     string         `json:"status"`
}

func (q *Queries) CountListProducts(ctx context.Context, arg CountListProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countListProducts,
		arg.SellerID,
		arg.CategoryID,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchProducts = `-- name: CountSearchProducts :one
SELECT COUNT(*)
FROM products
WHERE fts @@ plainto_tsquery('english', $1)
  AND status = 'active'
`

func (q *Queries) CountSearchProducts(ctx context.Context, plaintoTsquery string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchProducts, plaintoTsquery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (seller_id, category_id, title, description, price, tags)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, seller_id, category_id, title, description, price, tags, status, sales_count, rating, reviews_count, created_at, updated_at
`

type CreateProductParams struct {
	SellerID    uuid.UUID `json:"seller_id"`
	CategoryID  int32     `json:"category_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Price       float64   `json:"price"`
	Tags        []string  `json:"tags"`
}

type CreateProductRow struct {
	ID           uuid.UUID          `json:"id"`
	SellerID     uuid.UUID          `json:"seller_id"`
	CategoryID   int32              `json:"category_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Price        float64            `json:"price"`
	Tags         []string           `json:"tags"`
	Status       string             `json:"status"`
	SalesCount   int32              `json:"sales_count"`
	Rating       float64            `json:"rating"`
	ReviewsCount int32              `json:"reviews_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.SellerID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Tags,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Tags,
		&i.Status,
		&i.SalesCount,
		&i.Rating,
		&i.ReviewsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, seller_id, category_id, title, description, price, tags, status, sales_count, rating, reviews_count, created_at, updated_at
FROM products
WHERE id = $1
`

type GetProductByIDRow struct {
	ID           uuid.UUID          `json:"id"`
	SellerID     uuid.UUID          `json:"seller_id"`
	CategoryID   int32              `json:"category_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Price        float64            `json:"price"`
	Tags         []string           `json:"tags"`
	Status       string             `json:"status"`
	SalesCount   int32              `json:"sales_count"`
	Rating       float64            `json:"rating"`
	ReviewsCount int32              `json:"reviews_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Tags,
		&i.Status,
		&i.SalesCount,
		&i.Rating,
		&i.ReviewsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductSellerID = `-- name: GetProductSellerID :one
SELECT seller_id FROM products WHERE id = $1
`

func (q *Queries) GetProductSellerID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getProductSellerID, id)
	var seller_id uuid.UUID
	err := row.Scan(&seller_id)
	return seller_id, err
}

const incrementProductSales = `-- name: IncrementProductSales :exec
UPDATE products
SET sales_count = sales_count + $2
WHERE id = $1
`

type IncrementProductSalesParams struct {
	ID         uuid.UUID `json:"id"`
	SalesCount int32     `json:"sales_count"`
}

func (q *Queries) IncrementProductSales(ctx context.Context, arg IncrementProductSalesParams) error {
	_, err := q.db.Exec(ctx, incrementProductSales, arg.ID, arg.SalesCount)
	return err
}

const listProducts = `-- name: ListProducts :many
SELECT id, seller_id, category_id, title, description, price, tags, status, sales_count, rating, reviews_count, created_at, updated_at
FROM products
WHERE ($1::uuid IS NULL OR seller_id = $1::uuid)
  AND ($2::int IS NULL OR category_id = $2::int)
  AND ($3::numeric IS NULL OR price >= $3::numeric)
  AND ($4::numeric IS NULL OR price <= $4::numeric)
  AND status = $5
ORDER BY created_at DESC
LIMIT $7 OFFSET $6
`

type ListProductsParams struct {
	SellerID   pgtype.UUID    `json:"seller_id"`
	CategoryID pgtype.Int4    `json:"category_id"`
	MinPrice   pgtype.Numeric `json:"min_price"`
	MaxPrice   pgtype.Numeric `json:"max_price"`
	Status     string         `json:"status"`
	Offset     int32          `json:"offset_"`
	Limit      int32          `json:"limit_"`
}

type ListProductsRow struct {
	ID           uuid.UUID          `json:"id"`
	SellerID     uuid.UUID          `json:"seller_id"`
	CategoryID   int32              `json:"category_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Price        float64            `json:"price"`
	Tags         []string           `json:"tags"`
	Status       string             `json:"status"`
	SalesCount   int32              `json:"sales_count"`
	Rating       float64            `json:"rating"`
	ReviewsCount int32              `json:"reviews_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.SellerID,
		arg.CategoryID,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Tags,
			&i.Status,
			&i.SalesCount,
			&i.Rating,
			&i.ReviewsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, seller_id, category_id, title, description, price, tags, status, sales_count, rating, reviews_count, created_at, updated_at
FROM products
WHERE fts @@ plainto_tsquery('english', $1)
  AND status = 'active'
ORDER BY ts_rank(fts, plainto_tsquery('english', $1)) DESC
LIMIT $3 OFFSET $2
`

type SearchProductsParams struct {
	Query  string `json:"query"`
	Offset int32  `json:"offset_"`
	Limit  int32  `json:"limit_"`
}

type SearchProductsRow struct {
	ID           uuid.UUID          `json:"id"`
	SellerID     uuid.UUID          `json:"seller_id"`
	CategoryID   int32              `json:"category_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Price        float64            `json:"price"`
	Tags         []string           `json:"tags"`
	Status       string             `json:"status"`
	SalesCount   int32              `json:"sales_count"`
	Rating       float64            `json:"rating"`
	ReviewsCount int32              `json:"reviews_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error) {
	rows, err := q.db.Query(ctx, searchProducts, arg.Query, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProductsRow{}
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Tags,
			&i.Status,
			&i.SalesCount,
			&i.Rating,
			&i.ReviewsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET title       = $2,
    description = $3,
    price       = $4,
    tags        = $5,
    status      = $6,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, seller_id, category_id, title, description, price, tags, status, sales_count, rating, reviews_count, created_at, updated_at
`

type UpdateProductParams struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Price       float64   `json:"price"`
	Tags        []string  `json:"tags"`
	Status      string    `json:"status"`
}

type UpdateProductRow struct {
	ID           uuid.UUID          `json:"id"`
	SellerID     uuid.UUID          `json:"seller_id"`
	CategoryID   int32              `json:"category_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Price        float64            `json:"price"`
	Tags         []string           `json:"tags"`
	Status       string             `json:"status"`
	SalesCount   int32              `json:"sales_count"`
	Rating       float64            `json:"rating"`
	ReviewsCount int32              `json:"reviews_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Tags,
		arg.Status,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Tags,
		&i.Status,
		&i.SalesCount,
		&i.Rating,
		&i.ReviewsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductRating = `-- name: UpdateProductRating :exec
UPDATE products
SET rating = $2
WHERE id = $1
`

type UpdateProductRatingParams struct {
	ID     uuid.UUID `json:"id"`
	Rating float64   `json:"rating"`
}

func (q *Queries) UpdateProductRating(ctx context.Context, arg UpdateProductRatingParams) error {
	_, err := q.db.Exec(ctx, updateProductRating, arg.ID, arg.Rating)
	return err
}
