// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddToBalance(ctx context.Context, arg AddToBalanceParams) (Balance, error)
	AddWishlistItem(ctx context.Context, arg AddWishlistItemParams) (Wishlist, error)
	ClearCart(ctx context.Context, cartID int64) error
	CountBalanceTxByUsername(ctx context.Context, username string) (int64, error)
	CountListProducts(ctx context.Context, arg CountListProductsParams) (int64, error)
	CountOrdersByUsername(ctx context.Context, arg CountOrdersByUsernameParams) (int64, error)
	CountReviewsByProduct(ctx context.Context, productID uuid.UUID) (int64, error)
	CountSearchProducts(ctx context.Context, plaintoTsquery string) (int64, error)
	CreateBalanceTx(ctx context.Context, arg CreateBalanceTxParams) (BalanceTransaction, error)
	CreateOrder(ctx context.Context, username string) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateSeller(ctx context.Context, arg CreateSellerParams) (Seller, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeductFromBalance(ctx context.Context, arg DeductFromBalanceParams) (Balance, error)
	DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) (int64, error)
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	DeleteReview(ctx context.Context, id int64) (int64, error)
	GetAdminById(ctx context.Context, id uuid.UUID) (Admin, error)
	GetAdminByUsername(ctx context.Context, username string) (Admin, error)
	GetAdminUsernameByProductId(ctx context.Context, productID uuid.UUID) (string, error)
	GetAvgRatingByProduct(ctx context.Context, productID uuid.UUID) (float64, error)
	GetBalance(ctx context.Context, username string) (Balance, error)
	GetBalanceForUpdate(ctx context.Context, username string) (GetBalanceForUpdateRow, error)
	GetCartItems(ctx context.Context, cartID int64) ([]CartItem, error)
	GetCategoryBySlug(ctx context.Context, slug string) (GetCategoryBySlugRow, error)
	GetModerationByAdminId(ctx context.Context, adminID uuid.UUID) (Moderation, error)
	GetModerationByProductId(ctx context.Context, productID uuid.UUID) (Moderation, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetOrderByUID(ctx context.Context, uid uuid.UUID) (Order, error)
	GetOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error)
	GetProductPrice(ctx context.Context, id uuid.UUID) (float64, error)
	GetProductSellerID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetReviewByID(ctx context.Context, id int64) (Review, error)
	GetReviewsByProduct(ctx context.Context, arg GetReviewsByProductParams) ([]Review, error)
	GetSeller(ctx context.Context, arg GetSellerParams) (Seller, error)
	GetSellerByProductId(ctx context.Context, id uuid.UUID) (string, error)
	GetSession(ctx context.Context, username string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUID(ctx context.Context, uid uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetWishlistItems(ctx context.Context, username string) ([]Wishlist, error)
	IncreaseReviewsCount(ctx context.Context, id uuid.UUID) error
	IncreaseTotalSalesByProductId(ctx context.Context, arg IncreaseTotalSalesByProductIdParams) error
	IncrementProductSales(ctx context.Context, arg IncrementProductSalesParams) error
	ListActiveProducts(ctx context.Context, arg ListActiveProductsParams) ([]Moderation, error)
	ListBalanceTxByUsername(ctx context.Context, arg ListBalanceTxByUsernameParams) ([]BalanceTransaction, error)
	ListCategories(ctx context.Context) ([]ListCategoriesRow, error)
	ListOrdersByUsername(ctx context.Context, arg ListOrdersByUsernameParams) ([]Order, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	RemoveWishlistItem(ctx context.Context, arg RemoveWishlistItemParams) (int64, error)
	ReviewExistsByProductAndUser(ctx context.Context, arg ReviewExistsByProductAndUserParams) (bool, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error)
	SellerExistsByUsername(ctx context.Context, username string) (bool, error)
	SetUserRole(ctx context.Context, arg SetUserRoleParams) (User, error)
	UpdateCartItemQty(ctx context.Context, arg UpdateCartItemQtyParams) (CartItem, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateOrderTotal(ctx context.Context, arg UpdateOrderTotalParams) (Order, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error)
	UpdateProductRating(ctx context.Context, arg UpdateProductRatingParams) error
	UpdateSeller(ctx context.Context, arg UpdateSellerParams) (Seller, error)
	UpdateSellerRating(ctx context.Context, sellerID uuid.UUID) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertBalance(ctx context.Context, username string) (Balance, error)
	UpsertCart(ctx context.Context, username string) (UpsertCartRow, error)
	UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartItem, error)
	UserExistsByEmail(ctx context.Context, email string) (bool, error)
	UserExistsByUsername(ctx context.Context, username string) (bool, error)
	WishlistItemExists(ctx context.Context, arg WishlistItemExistsParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
