// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countReviewsByProduct = `-- name: CountReviewsByProduct :one
SELECT COUNT(*) FROM reviews WHERE product_id = $1
`

func (q *Queries) CountReviewsByProduct(ctx context.Context, productID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewsByProduct, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (product_id, username, rating, comment)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, username, rating, comment, created_at
`

type CreateReviewParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Username  string    `json:"username"`
	Rating    int16     `json:"rating"`
	Comment   string    `json:"comment"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.ProductID,
		arg.Username,
		arg.Rating,
		arg.Comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Username,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :execrows
DELETE FROM reviews WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReview, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAvgRatingByProduct = `-- name: GetAvgRatingByProduct :one
SELECT COALESCE(AVG(rating::float), 0)::float AS avg_rating
FROM reviews
WHERE product_id = $1
`

func (q *Queries) GetAvgRatingByProduct(ctx context.Context, productID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getAvgRatingByProduct, productID)
	var avg_rating float64
	err := row.Scan(&avg_rating)
	return avg_rating, err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, product_id, username, rating, comment, created_at
FROM reviews
WHERE id = $1
`

func (q *Queries) GetReviewByID(ctx context.Context, id int64) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Username,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewsByProduct = `-- name: GetReviewsByProduct :many
SELECT id, product_id, username, rating, comment, created_at
FROM reviews
WHERE product_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetReviewsByProductParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) GetReviewsByProduct(ctx context.Context, arg GetReviewsByProductParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, getReviewsByProduct, arg.ProductID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Username,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewExistsByProductAndUser = `-- name: ReviewExistsByProductAndUser :one
SELECT EXISTS(SELECT 1 FROM reviews WHERE product_id = $1 AND username = $2)
`

type ReviewExistsByProductAndUserParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Username  string    `json:"username"`
}

func (q *Queries) ReviewExistsByProductAndUser(ctx context.Context, arg ReviewExistsByProductAndUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, reviewExistsByProductAndUser, arg.ProductID, arg.Username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
