// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sellers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSeller = `-- name: CreateSeller :one
INSERT INTO sellers (username, display_name, description)
VALUES ($1, $2, $3)
RETURNING id, username, display_name, description, avatar_url, rating, total_sales, created_at, updated_at
`

type CreateSellerParams struct {
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
	Description string `json:"description"`
}

func (q *Queries) CreateSeller(ctx context.Context, arg CreateSellerParams) (Seller, error) {
	row := q.db.QueryRow(ctx, createSeller, arg.Username, arg.DisplayName, arg.Description)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Description,
		&i.AvatarUrl,
		&i.Rating,
		&i.TotalSales,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeller = `-- name: GetSeller :one
SELECT id, username, display_name, description, avatar_url, rating, total_sales, created_at, updated_at
FROM sellers
WHERE ($1::varchar IS NULL OR username = $1::varchar)
  AND ($2::uuid IS NULL OR id = $2::uuid)
  AND ($1::varchar IS NOT NULL OR $2::uuid IS NOT NULL)
`

type GetSellerParams struct {
	Username pgtype.Text `json:"username"`
	SellerID pgtype.UUID `json:"seller_id"`
}

func (q *Queries) GetSeller(ctx context.Context, arg GetSellerParams) (Seller, error) {
	row := q.db.QueryRow(ctx, getSeller, arg.Username, arg.SellerID)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Description,
		&i.AvatarUrl,
		&i.Rating,
		&i.TotalSales,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSellerByProductId = `-- name: GetSellerByProductId :one
SELECT username
FROM sellers
WHERE id=(SELECT p.seller_id FROM products p WHERE p.id=$1)
`

func (q *Queries) GetSellerByProductId(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getSellerByProductId, id)
	var username string
	err := row.Scan(&username)
	return username, err
}

const increaseTotalSalesByProductId = `-- name: IncreaseTotalSalesByProductId :exec
UPDATE sellers
SET total_sales = total_sales + $2
WHERE id = (SELECT p.seller_id FROM products p WHERE p.id = $1)
`

type IncreaseTotalSalesByProductIdParams struct {
	ID         uuid.UUID `json:"id"`
	TotalSales int32     `json:"total_sales"`
}

func (q *Queries) IncreaseTotalSalesByProductId(ctx context.Context, arg IncreaseTotalSalesByProductIdParams) error {
	_, err := q.db.Exec(ctx, increaseTotalSalesByProductId, arg.ID, arg.TotalSales)
	return err
}

const sellerExistsByUsername = `-- name: SellerExistsByUsername :one
SELECT EXISTS(SELECT 1 FROM sellers WHERE username = $1)
`

func (q *Queries) SellerExistsByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, sellerExistsByUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSeller = `-- name: UpdateSeller :one
UPDATE sellers
SET display_name = $2,
    description  = $3,
    avatar_url   = $4,
    updated_at   = NOW()
WHERE username = $1
RETURNING id, username, display_name, description, avatar_url, rating, total_sales, created_at, updated_at
`

type UpdateSellerParams struct {
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
	Description string `json:"description"`
	AvatarUrl   string `json:"avatar_url"`
}

func (q *Queries) UpdateSeller(ctx context.Context, arg UpdateSellerParams) (Seller, error) {
	row := q.db.QueryRow(ctx, updateSeller,
		arg.Username,
		arg.DisplayName,
		arg.Description,
		arg.AvatarUrl,
	)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Description,
		&i.AvatarUrl,
		&i.Rating,
		&i.TotalSales,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSellerRating = `-- name: UpdateSellerRating :exec
UPDATE sellers
SET rating     = (
    SELECT COALESCE(AVG(p.rating), 0)
    FROM products p
    WHERE p.seller_id = $1
),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateSellerRating(ctx context.Context, sellerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateSellerRating, sellerID)
	return err
}
