// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sellers.sql

package db

import (
	"context"
)

const createSeller = `-- name: CreateSeller :one
INSERT INTO sellers (username, display_name, description)
VALUES ($1, $2, $3)
RETURNING id, username, display_name, description, avatar_url, rating, total_sales, created_at, updated_at
`

type CreateSellerParams struct {
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
	Description string `json:"description"`
}

func (q *Queries) CreateSeller(ctx context.Context, arg CreateSellerParams) (Seller, error) {
	row := q.db.QueryRow(ctx, createSeller, arg.Username, arg.DisplayName, arg.Description)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Description,
		&i.AvatarUrl,
		&i.Rating,
		&i.TotalSales,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSellerByUsername = `-- name: GetSellerByUsername :one
SELECT id, username, display_name, description, avatar_url, rating, total_sales, created_at, updated_at
FROM sellers
WHERE username = $1
`

func (q *Queries) GetSellerByUsername(ctx context.Context, username string) (Seller, error) {
	row := q.db.QueryRow(ctx, getSellerByUsername, username)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Description,
		&i.AvatarUrl,
		&i.Rating,
		&i.TotalSales,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sellerExistsByUsername = `-- name: SellerExistsByUsername :one
SELECT EXISTS(SELECT 1 FROM sellers WHERE username = $1)
`

func (q *Queries) SellerExistsByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, sellerExistsByUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSeller = `-- name: UpdateSeller :one
UPDATE sellers
SET display_name = $2,
    description  = $3,
    avatar_url   = $4,
    updated_at   = NOW()
WHERE username = $1
RETURNING id, username, display_name, description, avatar_url, rating, total_sales, created_at, updated_at
`

type UpdateSellerParams struct {
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
	Description string `json:"description"`
	AvatarUrl   string `json:"avatar_url"`
}

func (q *Queries) UpdateSeller(ctx context.Context, arg UpdateSellerParams) (Seller, error) {
	row := q.db.QueryRow(ctx, updateSeller,
		arg.Username,
		arg.DisplayName,
		arg.Description,
		arg.AvatarUrl,
	)
	var i Seller
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Description,
		&i.AvatarUrl,
		&i.Rating,
		&i.TotalSales,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
