// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, full_name)
VALUES ($1, $2, $3, $4)
RETURNING username, uid, email, password_hash, full_name, avatar_url, role, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	FullName     string `json:"full_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Uid,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT username, uid, email, password_hash, full_name, avatar_url, role, is_active, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Uid,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUID = `-- name: GetUserByUID :one
SELECT username, uid, email, password_hash, full_name, avatar_url, role, is_active, created_at, updated_at
FROM users
WHERE uid = $1
`

func (q *Queries) GetUserByUID(ctx context.Context, uid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUID, uid)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Uid,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT username, uid, email, password_hash, full_name, avatar_url, role, is_active, created_at, updated_at
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Uid,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserRole = `-- name: SetUserRole :one
UPDATE users
SET role       = $2,
    updated_at = NOW()
WHERE username = $1
RETURNING username, uid, email, password_hash, full_name, avatar_url, role, is_active, created_at, updated_at
`

type SetUserRoleParams struct {
	Username string `json:"username"`
	Role     string `json:"role"`
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserRole, arg.Username, arg.Role)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Uid,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE users
SET password_hash = $1,
    updated_at = NOW()
WHERE username = $2
RETURNING username, uid, email, password_hash, full_name, avatar_url, role, is_active, created_at, updated_at
`

type UpdatePasswordParams struct {
	NewPassword string `json:"new_password"`
	Username    string `json:"username"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updatePassword, arg.NewPassword, arg.Username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Uid,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET full_name  = $2,
    avatar_url = $3,
    updated_at = NOW()
WHERE username = $1
RETURNING username, uid, email, password_hash, full_name, avatar_url, role, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	Username  string `json:"username"`
	FullName  string `json:"full_name"`
	AvatarUrl string `json:"avatar_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Username, arg.FullName, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Uid,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userExistsByUsername = `-- name: UserExistsByUsername :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) UserExistsByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
