// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wishlists.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addWishlistItem = `-- name: AddWishlistItem :one
INSERT INTO wishlists (username, product_id)
VALUES ($1, $2)
ON CONFLICT (username, product_id) DO NOTHING
RETURNING id, username, product_id, created_at
`

type AddWishlistItemParams struct {
	Username  string    `json:"username"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) AddWishlistItem(ctx context.Context, arg AddWishlistItemParams) (Wishlist, error) {
	row := q.db.QueryRow(ctx, addWishlistItem, arg.Username, arg.ProductID)
	var i Wishlist
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.ProductID,
		&i.CreatedAt,
	)
	return i, err
}

const getWishlistItems = `-- name: GetWishlistItems :many
SELECT id, username, product_id, created_at
FROM wishlists
WHERE username = $1
ORDER BY created_at DESC
`

func (q *Queries) GetWishlistItems(ctx context.Context, username string) ([]Wishlist, error) {
	rows, err := q.db.Query(ctx, getWishlistItems, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wishlist{}
	for rows.Next() {
		var i Wishlist
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.ProductID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWishlistItem = `-- name: RemoveWishlistItem :execrows
DELETE FROM wishlists
WHERE username = $1 AND product_id = $2
`

type RemoveWishlistItemParams struct {
	Username  string    `json:"username"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) RemoveWishlistItem(ctx context.Context, arg RemoveWishlistItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeWishlistItem, arg.Username, arg.ProductID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const wishlistItemExists = `-- name: WishlistItemExists :one
SELECT EXISTS(SELECT 1 FROM wishlists WHERE username = $1 AND product_id = $2)
`

type WishlistItemExistsParams struct {
	Username  string    `json:"username"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) WishlistItemExists(ctx context.Context, arg WishlistItemExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, wishlistItemExists, arg.Username, arg.ProductID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
