// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wishlists.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getWishlistItems = `-- name: GetWishlistItems :many
SELECT id, username, product_id, created_at
FROM wishlists
WHERE username = $1
ORDER BY created_at DESC
`

func (q *Queries) GetWishlistItems(ctx context.Context, username string) ([]Wishlist, error) {
	rows, err := q.db.Query(ctx, getWishlistItems, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wishlist{}
	for rows.Next() {
		var i Wishlist
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.ProductID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWishlistItem = `-- name: RemoveWishlistItem :execrows
DELETE FROM wishlists
WHERE username = $1 AND product_id = $2
`

type RemoveWishlistItemParams struct {
	Username  string    `json:"username"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) RemoveWishlistItem(ctx context.Context, arg RemoveWishlistItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeWishlistItem, arg.Username, arg.ProductID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const toggleWishlistItem = `-- name: ToggleWishlistItem :one
WITH deleted AS (
DELETE FROM wishlists dw
WHERE dw.username = $1 AND dw.product_id = $2
    RETURNING id, username, product_id, created_at
), inserted AS (
INSERT INTO wishlists (username, product_id)
SELECT $1, $2
WHERE NOT EXISTS (SELECT 1 FROM deleted)
    RETURNING id, username, product_id, created_at
    )
SELECT id, username, product_id, created_at, TRUE AS added
FROM inserted
UNION ALL
SELECT id, username, product_id, created_at, FALSE AS added
FROM deleted
`

type ToggleWishlistItemParams struct {
	Username  string    `json:"username"`
	ProductID uuid.UUID `json:"product_id"`
}

type ToggleWishlistItemRow struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	ProductID uuid.UUID          `json:"product_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Added     bool               `json:"added"`
}

func (q *Queries) ToggleWishlistItem(ctx context.Context, arg ToggleWishlistItemParams) (ToggleWishlistItemRow, error) {
	row := q.db.QueryRow(ctx, toggleWishlistItem, arg.Username, arg.ProductID)
	var i ToggleWishlistItemRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.ProductID,
		&i.CreatedAt,
		&i.Added,
	)
	return i, err
}

const wishlistItemExists = `-- name: WishlistItemExists :one
SELECT EXISTS(SELECT 1 FROM wishlists WHERE username = $1 AND product_id = $2)
`

type WishlistItemExistsParams struct {
	Username  string    `json:"username"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) WishlistItemExists(ctx context.Context, arg WishlistItemExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, wishlistItemExists, arg.Username, arg.ProductID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
