name: go

on:
  push:
    branches: [ "main", "bugfix" ]
  pull_request:
    branches: [ "main", "bugfix" ]

jobs:
  test:
    name: Test ServiceHub services
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Configure Git for private modules
        run: git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Set GOPRIVATE
        run: echo "GOPRIVATE=github.com/nhassl3/*" >> $GITHUB_ENV

      - name: Run tests
        run: make test
